BUILD_DIR=${BUILD_DIR-build}
BUILD_TYPE=${BUILD_TYPE-Debug}
GENERATOR=${GENERATOR-"Unix Makefiles"}
SRC_DIR=../..

mkdir -p "${BUILD_DIR}/${BUILD_TYPE}"
cd "${BUILD_DIR}/${BUILD_TYPE}"
cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -G "${GENERATOR}" ${SRC_DIR}

